//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Share.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BorrowedTool
    {
        public int id { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<int> tool_id { get; set; }
        public Nullable<int> user_id { get; set; }
        public bool approved { get; set; }
    
        public virtual Tool Tool { get; set; }
        public virtual User User { get; set; }
    }
}
